// Modesto Arrangement File
// Please keep the first 4 byte of this file.

modesto::TArrangement{
  modesto::TMIDITrack {
    name = "Bass"
    volume = 128
    pan = 64
    channel = 1
    bank = 1
    program = 39
    mute = false
    solo = false
    record = false
    monitor = false
    lock = false
    in = 1
    out = 1
    sequence = BASE64{
      "3qBmkCQvioU9kCQAk75lkCQzioU9kCQAkrMPkCQzjJRpkCQA74w1kCQvio0ZkCQA"
      "kp8YkCQ1icNBkCQAkZE1kCQ4iqwfkCQAld8kkCQ1jvYIkCQAge55kDAtjeJdkDAA"
      "go9HkCQ4js8akCQAgdhIkDAojoMFkDAAgZ1pkCQzkL9akCQAgYJWkDA1jo5BkDAA"
      "mTCQJDiQ5iOQJADpJZAwL42KZ5AwAIHRS5AkOJH3M5AkALQkkDAyjpo8kDAAgdlD"
      "kCQ4j7VCkCQAyDaQMDWNvS+QMACBzi+QJDiN8g2QJACByDKQMCqO7gqQMACBnUuQ"
      "JD2Q3CSQMDq2YpAkAIzILpAwAIK4FJAmOJDzWpAmAMN6kDI4jsxckDIAgedBkCY0"
      "j8R6kCYAgcgwkDI1j4Z/kDIAgcpfkCY+jtBIkCYAgephkDI4jY5mkDIAgt4+kCY6"
      "ka1qkCYA/HuQMj2N70OQMgCC5hiQJi+O5kyQJgCBwhaQMjWO5jKQMgCCkWWQJj6N"
      "4liQJgCB2GmQMjiO5lCQMgCB7xmQJjWO60+QJgCB2GiQMjONyHSQMgCCmQiQJj6R"
      "vgOQMj3dSpAmAI7IPpAyAORKkCRDkIpykCQAzDaQMDWQjlGQMACBmFaQJDiP7XuQ"
      "JAD9GZAwNI6aO5AwAIHnfpAkPY/vSJAkAOZBkDA9j5xRkDAAgbl6kCQ8j+EKkCQA"
      "gpYIkDA4jdBAkDAAgrQXkCRAkJIxkCQA0XOQMC+NuU6QMACDumuQJD6PyHiQJACB"
      "oUWQMDWPuSeQMACBuheQJDyOuSaQJACB5wKQMDKOhwKQMACB1EmQJD6S7FOQMD3X"
      "EZAkAIyLLJAwAIHOUZAmQJGFTJAyNa4YkCYAjtwHkDIAgZUOkCZAkY5HkCYAgcUU"
      "kDIyjp4WkDIAgcszkCY6j54PkCYAgZlskDI1i/c4kDIAg5AjkCYykMNSkCYA4CyQ"
      "MjiQngmQMgCB3mmQJjyP70CQJgCBzDGQMjWMu1KQMgCCkQuQJjyQ0wyQJgCmbpAy"
      "NI+GeJAyAIG0P5AmOI+SNZAmAIG2OpAyOY6xTZAyAIGfZJAmPo+2Q5AyPoHeaJAm"
      "AJC7d5AkP/g+kDIAjtAdkCQA4ieQMDyPzFuQMACBmCiQJD6QhnaQJAD2AZAwM43F"
      "CJAwAIHJbZAkQI/vZpAkAMQYkDA4j5B3kDAAgelAkCQ9kPc3kCQAgcRWkDA0kLUe"
      "kDAA7gGQJECQqEOQJACBm2qQMC2OxQGQMACB5WKQJD2RngOQJADja5AwNZDnX5Aw"
      "AL8AkCQ9kYUvkCQAgZ0IkDAyj68pkDAAjXaQJEORmWSQMEm6QpAkAI3OQpAwAIHK"
      "dpAmPJKSHpAyPoGbKZAmAI6YJpAmON1TkDIAkNY4kCYAjBiQMjKQjlGQMgDKV5Am"
      "Po/Ee5AmAOVmkDI+j9gzkDIAgYU7kCY6kJIrkCYAul6QMj+RyEuQMgDAX5AmNY+x"
      "RZAmAIGvAZAyQI/eDJAyAKJOkCY6j45okCYA5HWQMkCO+0WQMgC/QJAmOo/IVZAm"
      "AIG/F5AyPY/IWJAyAMM6kCY6j8B9kDJD9GCQJgCS3hiQJEyCjCeQMgCN30CQMDPh"
      "KJAkAI+xCJAwAIG3HJAkP5GCcpAkAIGOMJAwNY+aMpAwAIGpYpAkPo/yAZAkAIGe"
      "PJAwPY6lYZAwAIHWB5AkQI/RNpAkAIGFNZAwOpCWT5AwAIHMDJAkQJGMEZAkALQ4"
      "kDAyjoZskDAAgbk9kCRAkZYmkCQAgagBkDAqjoVEkDAA4QyQJD+R1EKQJADdEJAw"
      "PI33K5AwAILAV5AkQJHoVJAkAIsakDA/jYp3kDAAgZRekCY8k8FAkDJA+ECQJgCM"
      "rRyQMgCB8leQJjiUqUuQJgCnC5AyL47UTZAyAL8okCY6kpUBkCYAmVCQMjyPrWqQ"
      "MgDyQZAmOJH8EJAmAIw4kDI9jed0kDIAgYhUkCY9kOdDkCYAmVCQMjePmjKQMgCB"
      "u1yQJjqSmTyQJgDiaZAyOI+HHpAyAPg/kCZAkNwnkCYAu12QMkCO1RyQMgDnA5Am"
      "PZH2NJAyQM10kCYAkJ1ZkCRD3VCQMgCPigeQJADvY5AwM5C1PZAwAMIakCRAkaFh"
      "kCQAgYxVkDA+j/hdkDAAxTiQJDCR7XiQJACBgCyQMDmOoWKQMACBk26QJECR7zeQ"
      "JADVcpAwPY+WU5AwAIGZa5AkQI+9H5AkAIGZa5AwNI6iBpAwAIGmFpAkPpCaJ5Ak"
      "AIHuP5AwOY/nZ5AwAOJokCQ/kN5IkCQAga9hkDA1jfsJkDAAgcZykCQ9kYUPkCQA"
      "rwaQMECNvQ2QMACB8EaQJj6ShV+QJgCnC5AyOY+OWJAyAPJGkCY4k45bkCYAx3aQ"
      "MjiPjWCQMgCnCZAmOZGWJJAmAM42kDI9jfNLkDIAgbN8kCY6kvMwkCYAgYgTkDJA"
      "jtZJkDIAgbopkCZAj8EjkCYA/HuQMj6PtT2QMgCBqwSQJkCP2A+QJgCBmiyQMjyP"
      "iXiQMgCB0DCQJjyQgVmQJgCBiBOQMkCN53aQMgCBkG+QJjqQ4kWQJgCMOZAyRZHQ"
      "JJAkQ+kLkDIAjrhlkCQAgaJnkDA6jaIZkDAAgowskCQ9kfNVkCQA/nuQMDWPjjeQ"
      "MACBiBiQJECQnimQJADrIpAwOo6EBZAwAIGxApAkPpDwXJAkAMhWkDA1jtgXkDAA"
      "gatfkCRAj+NrkCQA8EGQMDKPwR2QMACBzw+QJDyQ8zuQJACByhiQMDyO3AqQMACB"
      "m0uQJD+PoXCQJAC3YpAwOY7gEZAwAIH5GpAkQJDFEJAkALdkkDA6kf8MkDAAvwCQ"
      "JECQuDeQJACZVJAwOpCSL5AwAIHtfJAkP4+WNJAkAPc/kDA1kLkckDAA9QCQJEKQ"
      "8lmQJADyYpAwPo2cYJAwAIG1GZAkQJHcBJAkALsekDA+j7kfkDAAgcNVkCQ/kONl"
      "kCQA6gWQMD+OmjeQMACCjmuQJECRgnOQJADwAZAwPI7zSZAwAILYI5AkOpCUb5Ak"
      "ANZxkDA6j6gIkDAAgZMQkCRDkotpkDA+8GCQJACL6WCQMACCniCQJkCR3AOQMj2t"
      "CJAmAI3MYpAyAIKFL5AmOpDIdZAmAIGhRJAyNY65SZAyAIG+d5AmPpD3N5AmAIHI"
      "NJAyNY2peZAyAPF9kCY6j+tmkCYAgdoGkDI5kYhxkDIApmqQJjmP6AeQJgCBoQmQ"
      "MjiP0FKQMgCBlG2QJjqQpWmQJgCBzC2QMjWOhwSQMgDHN5AmPI/cEZAmAIGdJpAy"
      "OI+HAJAyAIGYTpAmOo/pRJAyPK0HkCYAkdAJkCRF0VGQMgCP9SGQMDirKJAkAI/0"
      "PpAwAMNfkCRAkYUxkCQAgcFykDA6jophkDAAgaFokCRAkMB5kCQAgb52kDA+jvtA"
      "kDAAvwCQJD2ShmmQJADnJZAwOI65KZAwAIHbZ5AkQJGUa5AkAIGOb5AwNI3rcJAw"
      "AIHFFZAkPpKCbZAkAMJbkDA+jYFLkDAAgoYzkCRAkMcxkCQA4CmQMDyO0FqQMADG"
      "HZAkQJORW5AyNYOMB5AkAIzUA5AyAL9BkCY6kNgokCYAgYs0kDJDkJ4KkDIAgZJP"
      "kCY8kIU2kCYAzjWQMj2OwCOQMgDPdJAmOJDEd5AmAIGNUJAyOI3rdJAyAIGLEpAm"
      "OJLqNJAmANoMkDI+ja1XkDIA6mSQJjiPwS+QJgCBxUSQMjCOohKQMgCBiTaQJjOQ"
      "2yWQMiKBulmQJgCNoTyQMgCCgFOQJi2Q7wyQMhisdpAmAIuLVZAyAISpb5AmE5Of"
      "VpAmAPtjkDIQiLlFkDIAi69hkCYGidp3kCYA"
    }
  }
  modesto::TMIDITrack {
    name = "Drum"
    volume = 128
    pan = 64
    channel = 10
    bank = 1
    program = 25
    mute = false
    solo = false
    record = false
    monitor = false
    lock = false
    in = 1
    out = 1
    sequence = BASE64{
      "hO7JAJkkQ4+VFZkkAJGHMJkmRaPHHpkmAI3SQZkkQ4reTZkkAIeQapkmQ4LCMJko"
      "BoGFVJkoAI/tCZkmAI2rFJkkR5G3eJkkAI+6XpkmRZ2kNpkmAJPlEZkkRYmBZ5kk"
      "AIiMB5kmRY/DO5kmAJD8WZkkRY75dZkkAJKDXZkmSZucRpkmAJeXJJkkTIjWfpkk"
      "AImgVZkmUpCwH5kmAJGIEZkkR47DRZkkAJK2b5kmRZDLMZkmAKKIBpkkR4m7bZkk"
      "AIjhQpkmRZDSfpkmAJDOHpkkRY2YUZkkAJHKEJkmRZOkUJkmAJ+EHZkkRYj2Dpkk"
      "AImvTZkmQ4zPCZkmAJOjMpkkRY2sGJkkAJSqapkmQI6wDpkmAKKFRpkkQIjiOJkk"
      "AInZd5kmRY2+LJkmAJSDH5kkUovHM5kkAJTKW5kmQ5KFSZkmAJ+JGZkkP4ipdpkk"
      "AImIBJkmR47XF5kmAJKfP5kkRY2kPJkkAJPKXZkmQ4rHOZkmAKmjapkkQ4jTAJkk"
      "AIvDB5kmQ4vaWZkmAJXZDJkkSYqsKJkkAJXVaZkmRYrecZkmAKicVpkkQIj6KJkk"
      "AIi9bZkmTIn2CJkmAJbVZJkkRYn5ZpkkAJb8T5kmR4nPHZkmAKf5CpkkQ4ice5kk"
      "AIneVpkmQIqhbpkmAJWEVpkkQ4uoSJkkAJeraJkmQ4uRApkmAKfLIJkkP4i/SJkk"
      "AInmE5kmQ4qUdJkmAJbKC5kkRYu3fZkkAJabRZkmRYnmNJkmAKiNW5kkPYmsMJkk"
      "AIjOYpkmQ4ugSJkmAJfVH5kkSYy3eZkkAJSgTpkmQIisGJkmAKvGKJkkR4fmPJkk"
      "AIqEAJkmQ4qYdJkmAJfkWpkkSYmJH5kkAJf8C5kmQImYfJkmAKrpPpkkQ4jDSZkk"
      "AIjRAZkmQ4rmSZkmAJaqO5kkSYqwK5kkAJfeXZkmQInqK5kmAKmuJZkkSYigOJkk"
      "AIjpdZkmQ4moUZkmAJnRVJkkR4jqNpkkAJnCH5kmR4iJSpkmAKqJE5kkQIfqNZkk"
      "AIndV5kmRYqYdJkmAJe2UZkkRYnaeJkkAJbhHpkmR4mceJkmAKqYBZkkQ4qNQpkk"
      "AIfmPJkmP4zeXpkmAJTXEZkkQIuzfpkkAJfpWZkmQ4rPEZkmAKbiN5kkQIjTJpkk"
      "AInSOpkmQ4+RGpkmAJGXBZkkSZCVFJkkAJDWKpkmQ4mUe5kmAKjOOpkkQ4mFR5kk"
      "AIjPIJkmQIyRMpkmAJW+c5kkQ47WeJkkAJKwFZkmQI3LKJkmAKWQLZkkQ4i8D5kk"
      "AIj5CJkmQ4v9d5kmAJWfKZkkRZCJM5kkAJL/bZkmTIrabZkmAKaIUpkkQ4j7CJkk"
      "AInKX5kmQ47yB5kmAJHeApkkQ5CVEJkkAJKdfpkmRZPHIpkmAJ71I5kkQ4jeepkk"
      "AIrha5kmQ5GsIJkmAJCXapkkR5CRFpkkAJDeB5kmQ5aBU5kmAJv1NJkkQ4iVBJkk"
      "AInlc5kmQ4+gT5kmAJH9D5kkQ47yCZkkAJPDQ5kmQJTmTZkmAJ3ad5kkRYiNZ5kk"
      "AImII5kmRY7adpkmAJCnYJkkQ5GoJZkkAJDeJ5kmQ5faXpkmAJqgSZkkQImFRZkk"
      "AIm7KZkmRI+cUpkmAJKALpkkR5DDUJkkAJD7PpkmQ53WeZkmAJXpZJkkRIikWpkk"
      "AIjYWpkmQ4/eUpkmAJHeApkkQ5CJNZkkAJD5NJkmQ5ezeZkmAJuxOJkkRYj1cZkk"
      "AImUOpkmQ47LHpkmAJHWCpkkRY/2f5kkAJHMCpkmPZ+oCJkmAI/yJpkkQIm7ZJkk"
      "AIiwE5kmQIiJR5kmAIejBJkmNYm/QZkmAIeXJ5kmNYj2D5kmAIfgH5kmKIfuHJkm"
      "AInAYZkmPImFRJkmAA=="
    }
  }
  modesto::TMIDITrack {
    name = "Glocken"
    volume = 128
    pan = 64
    channel = 2
    bank = 1
    program = 10
    mute = false
    solo = false
    record = false
    monitor = false
    lock = false
    in = 1
    out = 1
    sequence = BASE64{
      "hO2rKpE3NYyqY5E+OIKueZE3AI6tL5E+AIOaYZE5OJC3e5E5AOBOkT4zj+8kkTcy"
      "xhmRPgCRkhCRNwD2O5E+OI+KYZE+AIlZkTk3j/hlkTkA1yuRPjiOvCiRNzXGHZE+"
      "AJLXAJE3AKJNkT40jv8ikT4A3E6ROTORwhORPj2rKJE5AI68B5E3NdstkT4AkbId"
      "kT4+qwqRNwCOtCqRPgCnDJE5NJDlBJE+PYHZSpE5AI+JH5E3NIGfSJE+AJC1fJE+"
      "Pvw9kTcAju4PkT4AijuROTiRr1qRPjytKJE5AI+/QZE3ONlNkT4AkKwgkT41gcl5"
      "kTcAj95OkTk1q0iRPgCQvBqRPjSBpwaROQCO8gyRNzTNdpE+AI/8WJE+PIKrAJE3"
      "AI7cVpE+AIw/kTk5kPR4kT48q0SROQCPrS6RNzOBxg6RPgCPuyuRPjisJ5E3AI3Y"
      "PZE5NdVykT4Ak4UHkTkAng6RPjqQt2GRNzjhKJE+AJGAeJE+OKxIkTcAkLQEkTk4"
      "rAKRPgCP5i6RPjitBpE5AJCkSZE3OLpCkT4Aj94HkT44gYt8kTcAjqc0kT4AsAOR"
      "OTSSnAORPjqsSJE5AI7uD5E3OIKydpE+AI/GWZE+OKwKkTcAj/VhkTk4rTmRPgCQ"
      "xmSROQCeE5E+PZCcLJE3OIHiYpE+AI7VXpE+NMl2kTcAjr4pkT4ApmmROTqRvnSR"
      "PjrtBZE5AJCIKZE3OoGXO5E+AI/8P5E+OtFzkTcAkO9AkT4AlRaROTiPr02RPjqB"
      "gDOROQCPyjyRNziB5SKRPgCPiF6RPjjVcpE3AI/aUZE5OPBikT4AjupqkTkApxCR"
      "PjmR0QiRNzr4SpE+AI66PJE+NNFUkTcAkKxGkTk6xjqRPgCPp0+RPjjRc5E5AJH9"
      "EJE3OK1okT4Ajt11kT46gb43kTcAkJ1wkT4A5jWROTqRwyWRPjiBhVOROQCQwDyR"
      "Nz6CrniRPgCPkDyRPjjlBpE3AJCLeJE5NbJmkT4AkIwWkT46zXSROQCQu12RNzSB"
      "gxmRPgCO/QSRPjjRcpE3AJCnSZE+AOsDkTk4kMlVkT44gYlJkTkAkMQDkTc+zXeR"
      "PgCPwwCRPjirB5E3AI+dEZE+AJRxkTk9kIp8kTkAgeodkT46jsojkTc0gf02kT4A"
      "j5hzkT41rUqRNwCPlDiROTquaJE+AJCce5E+NYHeVZE5AJDBAJE3OoGsfJE+AI+Q"
      "WZE+OLZjkTcAkJEtkT4AojGROTmQo2yRPjqBnyeROQCQuj6RNzyBhDqRPgCPzXaR"
      "PjrhKZE3AJClbJE+AIl4kTk0kKVqkTkAgaMkkT40j7Z5kTc1goF/kT4AjrpMkT46"
      "tl+RNwCPpXOROUCtY5E+AJH/FJE5ANNRkT44j/RikTc+gacnkT4Aj7tjkTcAiXeR"
      "PjqPyGCRPgDuIZE5OpCNV5E+NdVNkTkAkYszkTc99G+RPgCQqnaRPjzCO5E3AJGE"
      "F5E5OoGANpE+AJDPMpE5AKZqkT44j/1DkTc4gqV9kT4AkNxskT49rGaRNwCO53KR"
      "PgDnBpE5OY/fMJE5AJUkkT49kPxokTc6gZNskT4AkKQKkTcAqyiRPjeQxByRPgCt"
      "I5E5N5DkCZE5AIGOUJE+OpCPNpE3OILdQpE+AI+cFJE3AIoXkT45jv8mkTk4gYgT"
      "kT4AkpYDkTkAgZBWkT4+j5AXkTc6gpkHkT4Aj7NmkTcAgbF+kT44jpEjkT4Agdhm"
      "kTk4kKRpkTkA3g6RPj6QrmuRNz30XJE+AJCgKZE3AJlRkT49j8IAkTk+qwiRPgCQ"
      "oWmROQCB+VuRPjqO8QiRPgC0R5E3MpGpP5E3AIwVkT43kL0ekT4AgYQVkTk0kP17"
      "kTkAgbBhkT44kPUXkTc6gYAckT4Aj7EskTcAgYxQkT49jvFskTk40XWRPgCQtH6R"
      "OQCBo2ORPj6QnA+RNzqB5kORPgCP8WaRNwDtA5E+QI7pMpE5PIGAOJE+AI/jT5E5"
      "AIGQTpE+PpCUEZE3OoG+NpE+AI/bc5E3AMt2kT44kKhNkTk4qwSRPgCQz3GROQCV"
      "FJE+PZD0QJE3PeJmkT4AkZYvkT46rQSRNwCP/FOROT6tUZE+AJHXCpE5AKZqkT45"
      "kLdgkTc4gYgWkT4Aj+9mkTcAlHSRPjiP7geROTisBZE+AJHUC5E+M6sqkTkAj9VT"
      "kTc+gb42kT4AkJlykTcA1i2RPj6O+WqROTiBtjqRPgCQlhSROQCBhFORPj2P3hGR"
      "NzyC3UCRPgCNzCaRNwC/EZE+PpCAUZE5PIGTaJE+AI7QIJE5ANZ3kT46keFakTc6"
      "gc8skT4Aj6trkTcAxzyRPjqQ2QqROTjoCZE+AI76ZZE5AO1jkT49j8p8kTc4gf0z"
      "kT4AkIoZkTcAgahFkT46ju0tkTk6+GCRPgCPlnKRPj6rP5E5AJDkMZE3QIKdApE+"
      "AJCfT5E3AJA0kT4/kKt1kTk6gZBFkT4AkId1kTkAnhKRPj+Q1S6RNz6BulqRPgCO"
      "/2KRPj2BgDyRNwCQlA+ROTiBrwKRPgCP4RGROQCjCZE+PZCYDpE3OoO4EpE+AI7e"
      "VJE3AIp8kT4/kMcUkTk4gc8xkT4Aj4J/kTkAijaRPj2QgCORNz6Bwg+RPgCPi0SR"
      "Pj30XpE3AJD/GZE5P4GQEJE+AJDkCZE+P90pkTkAj+AQkTdAgdVtkT4Aj59PkTcA"
      "nguRPj2R2SyROT2BhDqRPgCP3VCRPjyrZZE5AJDGWpE3PILdP5E+AI2OBpE3AOYN"
      "kT4+kJAPkTk8gZdrkT4Aju8PkTkAgd57kT46j8MJkTc4gdFvkT4AjqkvkTcA8UaR"
      "Pj6PpC+ROTiBtlmRPgCPzB2ROQCCjEeRPj2PxyGRNziB7XyRPgCPoFSRNwDWEZE+"
      "M5CqJ5E+AJAzkTk0kKErkTkAgcN1kT4oj6xPkTc1gYgRkT4Aj/EpkTcAqySRPjSQ"
      "nFGROTiBj3CRPgCO0T6ROQCB0GuRPjKQ1y6RNzWCk2qRPgCN2ACRNwDqZZE+OI/+"
      "HZE5NPRikT4AjsBlkTkAgocykT44kKpGkTc4gsoIkT4AjdwBkTcAgak9kT41j9V2"
      "kTk8gfB9kT4AjopIkTkAgppBkT4zkMR6kTcwgeUikT4AjqVbkTcAv1WRPjqQknWR"
      "PgCMGJE5PZCxQpE5AIGULZE+PZCiSpE3QIGNVZE+AJC0XJE3APp+kT41j859kTk4"
      "gcI0kT4AkLR9kTkAgbQAkT46j/1SkTc5gtFykT4Ajec6kTcAgaBIkT46jrMQkTk6"
      "gasgkT4Aj4RgkTkAgf1tkT48kKNykTc9gqg9kT4AjsY3kTcAlH+RPj2Qi3mROT6t"
      "BpE+AJDUT5E5AO4EkT46kNFykTc+gbZakT4AjtI8kTcAq0uRPjeO3DWRPgDQc5E5"
      "Mo/YM5E5AIGAOpE+LY74ZZE3KoLRapE+AJKOLZE3AJBQkT4qjbFXkT4AgcxQkTci"
      "jsshkTcA2BqRPhyMrVSRPgCCyUiRNxeWuRqRNwA="
    }
  }
}